version: "3"
services:
  client:
    container_name: react
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    links:
      - app
    networks: 
      - webappnetwork
  app:
    container_name: nodejs
    #restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "49160:8080"
      - "9229:9229" #debug
    volumes:
      - ./server:/usr/src/app
    links:
      - mongo
    networks: 
      - webappnetwork
  mongo:
    container_name: mongo
    image: mongo
    #volumes:
      #- ./data:/data/db
    ports:
      - "27017:27017"
    networks: 
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge