version: "3"
services:
  app:
    container_name: nodejs
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "49160:8080"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    #volumes:
      #- ./data:/data/db
    ports:
      - "27017:27017"
